spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/dev_db
    username: dev_user
    password: dev_password
    driver-class-name: org.postgresql.Driver

    logging:
      level:
        root: INFO
        com.sprint.mission.discodeit: DEBUG
        org.hibernate.SQL: DEBUG

    jpa:
      hibernate:
        ddl-auto: update

    server:
      port: 8080