spring:
  application:
    name: discodeit
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 30MB
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/discodeit
    username: discodeit_user
    password: discodeit1234
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

logging:
  level:
    root: info
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace
    org.springframework.security: trace

discodeit:
  storage:
    type: local
    local:
      root-path: .discodeit/storage
  admin:
    username: admin
    email: admin@discodeit.com
    password: ${ADMIN_PASSWORD:admin1234}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,loggers