server:
  port: 8080
spring:
  config:
    activate:
      on-profile: prod
  #  sql:
  #    init:
  #      mode: always
  #      schema-locations: classpath:schema.sql
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    driver-class-name: org.postgresql.Driver
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

logging:
  level:
    root: info
    org.hibernate.SQL: off
    org.hibernate.orm.jdbc.bind: off
    org.springframework.web: info
